accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signin', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('recover/', views.pass_recovery, name='recover'),
    path('logout', views.logout, name="logout"),
    path('recover/sent', views.sent_link, name='sent-link'),
]

microapi_dashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("homepage.urls")),
    # path('blog/', include('blog')),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('dashboard/', include('user_dashboard.urls', namespace="dashboard")),
    path('', include("api_docs.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user_dashboard/urls.py
from django.urls import path, re_path
from . import views

app_name = "user_dashboard"

urlpatterns = [
    path('', views.api_list, name='dashboard'),
    re_path(r'^adding_api/(?P<id>\d+)$', views.adding_api, name='adding_api'),
    re_path(r'^rmv_api/(?P<id>\d+)$', views.rmv_api, name='rmv_api'),
    path('configure_api/', views.configure_api, name='configure_api'),
    path('logout/', views.logout, name='logout'),
    path('settings/', views.settings, name='settings')
]

user_dashboard/models.py
from django.db import models
# from accounts.models import User

#Models for all the API's in the database
class ApiList(models.Model):
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    stats = models.CharField(max_length=255, default='3req/hr')
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class ActiveApiList(models.Model):
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    stats = models.CharField(max_length=255)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Project(models.Model):
    name = models.CharField(max_length=255)
    # user_id = models.ForeignKey(User, related_name='projects', on_delete=models.CASCADE)
    token = models.UUIDField()

    def __str__(self):
        return self.name

user_dashboard/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView
from . models import ApiList, ActiveApiList
from accounts.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from homepage.views import index

@login_required(login_url='/accounts/signin')
def api_list(request):
    user = User.objects.all()
    all_apis = ApiList.objects.order_by('title')
    return render(request, 'user_dashboard/dashboard.html', {'all_apis':all_apis})


def adding_api(request, id):
    add_to_api = ApiList.objects.get(id=id)
    user = request.user
    print(user)
    User.add_api(api = add_to_api, name = user)
    #all_apis = ApiList.objects.order_by('title')
    return redirect('/dashboard')
    #return render(request, 'user_dashboard/dashboard.html', {'all_apis':all_apis})

def rmv_api(request, id):
    add_to_api = ApiList.objects.get(id=id)
    user = request.user
    user.api_list.remove(add_to_api)
    return redirect('/dashboard')


@login_required(login_url='/accounts/signin')
def configure_api(request):
    return render(request, 'user_dashboard/configure_api.html')


def logout(request):
    auth.logout(request)
    return redirect('index')


def settings(request):
    return render(request, 'user_dashboard/acct_settings.html')

templates/user_dashboard/acct_settings.html
{% extends 'user_dashboard/dash_base.html' %}

{% block content %}
{% load static %}

<div id="settings">

  <div>
    <div class="main__title">
      <h1>Account Settings</h1>
      <p>Set your preference, help us personalize your experience and make account changes here</p>
    </div>

    <div class="main__content__heading">
      <div></div>

      <div>
        <h4>Profile</h4>
      </div>
    </div>

    <div class="main__content">
      <div class="main__content__menu">
        <ul>
          <li class="active"><b>Profile</b></li>
          <li><b>Password</b></li>
          <li><b>Projects</b></li>
        </ul>
      </div>

      <section class="main__content__tabs">
        
        <article id="profile-tab">
          <div class="profile__details">
            <div class="profile__image">
              <i class="far fa-user"></i>
            </div>
  
            <div class="btn-container">
              <button class="primary-btn custom-btn">Upload New Image</button>
  
              <p>Remove</p>
            </div>
          </div>

          <div class="edit__profile__form">
            <form>

              <label>
                <b>Username</b>
                <input type="text" placeholder="Kadet">
              </label>

              <label>
                <b>Email</b>
                <input type="text" placeholder="techkadet@gmail.com">
              </label>

              <button class="primary-btn custom-btn">Save Changes</button>

            </form>
          </div>
        </article>
        
      </section>
    </div>

  </div>

</div>

{% endblock %}

templates/user_dashboard/configure_api.html
{% extends 'user_dashboard/dash_base.html' %}

{% block content %}
{% load static %}

        <div class="configure_blog">
          <div class="configure_blog__main row ml-3 mt-4 mr-3">
          <!-- code goes here-->
          <div class="configure_blog_sect1__cont1 col-lg-8 ">
            <div class="configure_blog_sect1__cont2">
              <h2>Configure Blog Api</h2>
              <p>This is a map of user data. It contains sign up information needed from the user before auth</p>
              <div class="configure_blog_sect1__cont2__apigraph">
                <h5>API Usage</h5>
                <div class="configure_blog_sect1__cont2__apigraph__cont">
                  <div class="apistatus"><div class="apistatus__dot"></div>Status</div>
                  <div class="apistats"><div class="apistats__dot"></div>Stats</div>
                  <div class="apigraph_cont"><canvas id="apigraph"></canvas>  </div>
                </div>
              </div>
              <form>
                <div class="box">
                  <label for="apiKey">API Key</label>
                  <input type="text" placeholder="23pcei3434kef">
                </div>
                <div class="box">
                  <label for="baseId">Base ID</label>
                  <input type="text" placeholder="94nfkkeo454nkf">
                </div>
                <div class="box">
                  <label for="blogApi">Content Type</label>
                  <input type="text" placeholder="Blog API">
                </div>
                <div class="box">
                  <label for="node">Node type</label>
                  <input type="text" placeholder="Blog API">
                </div>
                <div class="row ml-0 mr-0 pl-0 pr-0">
                  <div class="box_small box_small--modifier1">
                    <label for="servers">Allowable Servers</label>
                    <input type="text" placeholder="API Administrators">
                  </div>
                  <div class="box_small box_small--modifier2">
                    <label for="service">Ajax Proxy Service</label>
                    <input type="text" placeholder="www.domain.com">
                  </div>
                  <div class="box_small box_small--modifier3">
                    <label for="token">API Token</label>
                    <input type="text" placeholder="Blog API">
                  </div>
                  <div class="box_small box_small--modifier4">
                    <label for="Authentication">Authentication</label>
                    <input type="text" placeholder="Blog API">
                  </div>
                  <div class="box_small box_small--modifier5">
                    <label for="Porthost">Port host</label>
                    <input type="text" placeholder="www.domain.com">
                  </div>
                  <div class="check_box ">
                    <label for="transport">Transport level Security</label>
                      <div class="pretty p-icon">
                        <input type="checkbox" />
                        <div class="state">
                          <i class="icon material-icons">done</i>
                          <label><span class="spacer"></span>Http</label>
                        </div>
                      </div>
                      <div class="pretty p-icon">
                        <input type="checkbox" />
                        <div class="state">
                          <i class="icon material-icons">done</i>
                          <label><span class="spacer"></span>Https</label>
                        </div>
                      </div>
                  </div>
                </div>
              </form>
              <div class="configure_blog_sect1__cont2__footer">
                <a><i class="fas fa-save"></i>Save</a>
              </div>
            </div>
          </div>
          <div class="configure_blog_sect2 col-lg-3 ml-3 mb-4">
            <div class="configure_blog_sect2__pie">
              <h4>Statistics</h4><hr>
              <p>Overall API Usage</p>
              <div class="pie_chart"><canvas id="pie"></canvas></div>
            </div>
            <div class="configure_blog_sect2__doc">
              <h4>Documentation<i class="fas fa-search"></i></h4><hr>
              <ul>
                <li><a href="#">Sign up with email</a></li>
                <li><a href="#">Sign in with facebook</a></li>
                <li><a href="#">Sign in with Google</a></li>
                <li><a href="#">Confirm password</a></li>
                <li><a href="#">Change password</a></li>
                <li><a href="#">Reset password</a></li>
                <li><a href="#">Confirm password</a></li>
                <li><a href="#">Reset password</a></li>
              </ul>
              <a class="view__doc"><i class="fas fa-file"></i>View doc</a>
          </div>
          <div class="configure_blog_sect2__git">
            <a href="#">Open GitHub</a>
          </div>
          <div class="configure_blog_sect2__sample">
            <h4>Code sample</h4><hr>
            <p>Select Language</p>
            <select name="language" id="language">
              <option value="python">Python</option>
              <option value="java">Java</option>
              <option value="javascript">Javascript</option>
            </select>
            <h5>Easily download code sample of different programming languages</h5>
            <a href="#"><i class="fas fa-book-open"></i>view sample</a><hr>
            <a href="#"><i class="fas fa-download"></i>Download</a>
          </div>
        </div> 
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/user_dashboard/dash_base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta name="Description" content="Enter your description here" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">
  <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/material-design-icons/3.0.1/iconfont/material-icons.min.css">
  <link rel="stylesheet" href=" https://cdn.jsdelivr.net/npm/pretty-checkbox@3.0/dist/pretty-checkbox.min.css">
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css">
  <link rel="stylesheet" href="{% static 'css/style.min.css'%}">
  <title>MicroAPI - Dashboard</title>
</head>

<body>
  <!-- dashbord -->
  <div id="dashboard">
    <!-- dashboard side bar -->
    <div class="sidebar">
      <div class="sidebar__logo">
        <a href="{% url 'index' %}"><img src="{% static 'img/logo-alt.svg' %}" alt=""></a>
      </div>

      <div class="sidebar__section">
        <div class="sidebar__section__header">
          <h5>Projects <i class="fas fa-angle-up"></i></h5>
          <ul class="sidebar__section__header__list">
            <li>
              <a href="#">Acme Project</a>
              <!-- <div class="pretty p-icon">
                <input type="checkbox" />
                <div class="state">
                  <i class="icon material-icons">done</i>
                  <label><span class="spacer"></span>Acme Project's</label>
                </div>
              </div> -->
            </li>

            <li>
              <a href="#" class="inactive">Sentry's Prrojects</a>

              <!-- <div class="pretty p-icon">
                <input type="checkbox" />
                <div class="state">
                  <i class="icon material-icons">done</i>
                  <label><span class="spacer"></span>Sentry Project's</label>
                </div>
              </div> -->

            </li>
            <button class="add-new" type="button" class="btn btn-primary" data-toggle="modal" data-target="#addApiModal">
              <span>+</span>
              <a href="#">New project</a>
            </button>

            <!-- Modal -->
            <div class="modal fade" id="addApiModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" data-backdrop="static" data-keyboard="false">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Add Project</h5>
                    <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button> -->
                  </div>
                  <div class="modal-body">

                    <div class="form-group">
                      <label for="project name"></label>
                      <input type="text"
                        class="form-control" name="project name" id="" aria-describedby="helpId" placeholder="Enter project name">
                      <small id="helpId" class="form-text text-muted"></small>
                    </div>

                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary">Add Project</button>
                  </div>
                </div>
              </div>
            </div>
            <!-- Modal end -->
          </ul>
        </div>
        <div class="sidebar__section__content">
          <div class="sidebar__section__content__sub">
            <h5>Tools <i class="fas fa-angle-up"></i></h5>
            <ul class="sidebar__section__content__sub__list">
              <li>
                <a href="#">MicroAPI</a>
              </li>
              <li>
                <a href="#">Frontends</a>
              </li>
              <li>
                <a href="#">Database</a>
              </li>
            </ul>
          </div>
          <div class="sidebar__section__content__sub">
            <h5 class="sidebar__section__content__sub__title">Accounts <i class="fas fa-angle-up"></i></h5>
            <ul class="sidebar__section__content__sub__list">
              <li>
                <a href="{% url 'dashboard:settings' %}">Account settings</a>
              </li>
              <li>
                <a href="{% url 'dashboard:logout' %}">Sign out</a>
              </li>
            </ul>
          </div>
          <div class="sidebar__section__content__sub">
            <h5 class="sidebar__section__content__sub__title">Contribute <i class="fas fa-angle-up"></i></h5>
            <ul class="sidebar__section__content__sub__list">
              <li>
                <a href="#">Contribute to MicroAPI</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="content">
      <header>
        <a class="menu"><i class="fas fa-bars"></i></a>
        <div class="profile_section">
          <a type="button" data-toggle="modal" data-target="#notificationModal"><i class="far fa-bell"></i></a>
          
          <!-- Modal -->
          <div class="modal fade" id="notificationModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" data-backdrop="false" data-keyboard="false">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLongTitle">All Notifications</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">

                  <div class="notification-content">

                  </div>

                </div>
                <!-- <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                  <button type="button" class="btn btn-primary">Add Project</button>
                </div> -->
              </div>
            </div>
          </div>
          <!-- Modal end -->

          <div class="profile_section__pix">{{user.username}}<a><i class="far fa-user"></i></a></div>
        </div>
      </header>

  {% block content %}


  {% endblock %}
  

<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script>  -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script src="{% static 'js/dashboard_sidebar.js' %}"></script>
<script src="{% static 'js/dashboard.js' %}"></script>
<script src="{% static 'js/configure_api.js' %}"></script>
</body>

</html>

templates/user_dashboard/dash_template.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">
<link rel="stylesheet" href="../assets/css/style.min.css">
<title>MicroAPI - Dashboard starter</title>
</head>
<body>
  <!-- dashbord -->
	<div id="dashboard">
        <!-- dashboard side bar -->
        <div class="sidebar">
            <div class="sidebar__logo">
                <a href="../index.html"><img src="../assets/img/logo-alt.svg" alt=""></a>
            </div>

            <div class="sidebar__section">
                <div class="sidebar__section__header">
                    <h5>Projects  <i class="fas fa-angle-up"></i></h5>
                    <ul class="sidebar__section__header__list">
                        <li><input type="checkbox"><p>Acme Project's</p></li>
                        <li><input type="checkbox"><p>Sentry Project's</p></li>
                        <button class="add-new"><span>+</span><p>New project</p></button>
                    </ul>
                </div>
                <div class="sidebar__section__content">
                    <div class="sidebar__section__content__sub">
                        <h5>Tools <i class="fas fa-angle-up"></i></h5>
                        <ul class="sidebar__section__content__sub__list">
                            <li><p>MicroAPI</p></li>
                            <li><p>Frontends</p></li>
                            <li><p>Database</p></li>
                        </ul>
                    </div>
                    <div class="sidebar__section__content__sub">
                        <h5 class="sidebar__section__content__sub__title">Accounts <i class="fas fa-angle-up"></i></h5>
                        <ul class="sidebar__section__content__sub__list">
                            <li><p>Account settings</p></li>
                            <li><p>Sign out</p></li>
                        </ul>
                    </div>
                    <div class="sidebar__section__content__sub">
                        <h5 class="sidebar__section__content__sub__title">Contribute <i class="fas fa-angle-up"></i></h5>
                        <ul class="sidebar__section__content__sub__list">
                            <li><p>Contribute to MicroAPI</p></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="content">
            <header>
                <a class="menu"><i class="fas fa-bars"></i></a>
                <div class="profile_section">
                    <a><i class="far fa-bell"></i></a>
                    <div class="profile_section__pix">Samuel Eze<a><i class="far fa-user"></i></a></div>
                </div>
            </header>
            <div>
            <!-- code goes here-->
            </div>
        </div>
    </div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script> 
<script src="../assets/js/dashboard_sidebar.js"></script>
</body>
</html>

templates/user_dashboard/dashboard.html
{% extends 'user_dashboard/dash_base.html' %}

{% block content %}

{% load static %}
          <!-- Main dashboard content starts here -->

          <div class="dashboard__main">
            <!-- code goes here-->
            <div class="dashboard__title">
              <h1>Dashboard</h1>
            </div>

            <div class="dashboard__subtitle">
              <h3>Active APIs</h3>
            </div>

              <section id="container">
                <article class="dropBox active-row">

                  <div id="empty-api" class="empty-api"
                    style="display:none; flex-direction:column; justify-content:center; align-items:center; width: 100%">
                    <div className="icon">
                      <span class="material-icons" style="font-size: 65px; color: lightgrey">cloud_off</span>
                    </div>

                    <div className="text" style="text-align:center;">
                      <h4 style="color: lightgrey">There's nothing here</h4>
                      <p style="color: lightgrey;">Drag from available APIs or use the add button to add new API</p>
                    </div>
                  </div>
                  
                  
                  <!-- Single box -->
                  {% for obj in all_apis %}

                  {% if obj in request.user.api_list.all %}
                  <div class="dragBox active-box">
                    <div class="api__box">
                      <div class="api__box__shadow">
                        <div class="api__box__inner">
                          <div class="api__box__heading">
                              <h5>{{ obj.title }}</h5>  
                              <!-- toggle -->
                              <div class="pretty p-switch p-fill">
                                <input type="checkbox" />
                                <div class="state p-success">
                                    <label></label>
                                </div>
                              </div>
                              
                          </div>
                          <div class="api__box__text">
                            <small>{{ obj.description }}</small>
                          </div>
                          <div class="api__box__stats">
                            <p>Stats <br>
                              <span>{{ obj.stats }}</span>
                            </p>
                          </div>
                          <div class="api__box__buttons">
                            <a href="{% url 'dashboard:configure_api' %}"><button class="primary-btn">Configure</button></a>
                            
                            <!-- <input type="radio" name="" id=""> -->
                            <!-- success -->
                            <div class="prindex.html pretty p-default p-round p-toggle">
                              <input type="checkbox" />
                              <div class="state p-success p-on">
                                  <label></label>
                              </div>
                              <div class="state p-danger p-off">
                                  <label></label>
                              </div>
                            </div>
                          </div>
                          <div>
                            <a href="{% url 'dashboard:rmv_api' obj.id %}"><button>- Remove</button></a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div> <!-- Single box end -->
                  {% endif %}

                  {% endfor %}
                </article>

                <div class="search-box">
                  <div class="search-box__head">
                    <h3>Available APIs</h3>
                  </div>
                  <div class="search-box__input">
                    <label for="search">
                      <i class="fas fa-search"></i>
                      <input type="text" placeholder="Search for APIs">
                    </label>
                  </div>
                </div>
                
                <article class="dropBox inactive-row">
                  
                  <!-- Single box -->
                  {% for all_api in all_apis %}
                  {% if all_api not in request.user.api_list.all %}
                  <div class="dragBox inactive-box">
                    <div class="api__box">
                      <div class="api__box__shadow">
                        <div class="api__box__inner">
                          <div class="api__box__heading">
                            <h5>{{ all_api.title }}</h5>
                            <!-- toggle -->
                            <div class="pretty p-switch p-fill">
                              <input type="checkbox" />
                              <div class="state p-success">
                                <label></label>
                              </div>
                            </div>
                          </div>
                          <div class="api__box__text">
                            <small>{{ all_api.description }}</small>
                          </div>
                          <div class="api__box__stats">
                            <p>Stats <br>
                              <span>{{ all_api.stats }}</span>
                            </p>
                          </div>
                          <div class="api__box__buttons">
                            <a href="{% url 'dashboard:adding_api' all_api.id %}"><button class="secondary-btn">+ Add API</button></a>
                            <!-- <input type="radio" name="" id=""> -->
                            <!-- success -->
                            <div class="prindex.html pretty p-default p-round p-toggle">
                              <input type="checkbox" />
                              <div class="state p-success p-on">
                                <label></label>
                              </div>
                              <div class="state p-danger p-off">
                                <label></label>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div> <!-- Single box end -->
                  {% endif %}
                  {% endfor %}
                </article>
                
              </section>


            </div>
          </div>
        </div>
    </div>
<script type="text/javascript">
$('.add_api').click(function() {
var id;
id = $(this).attr("add_to_active");
$.ajax(
  {
    type = 'POST',
    url = 'active_api',
    data: {
      all_api_id : id
    },
    success: function(data) {

    }
  }
)
})


</script>

{% endblock %}